name: Development

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_call:

jobs:
  quality:
    name: Code Quality
   
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm install
    
    - name: Linting and fix
      run: npm run lint:fix --if-present

    - name: Prettier and fix
      run: npm run prettier:fix --if-present

  test_and_coverage:
    name: Test And Code Coverage
    needs: quality
 
    runs-on: ubuntu-latest
    
    environment: development

    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['5.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - name: Set environment
      run: cp .env.example .env
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
    
    - name: Test & Coverage
      run: npm run coverage:ci --if-present
