name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  env:
    name: Prepare Environment
    
    runs-on: ubuntu-latest
    
    environment: development
    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      SECRET: ${{ secrets.PGP_PASSPHRASE }}
      
    outputs:
      MONGODB_URL: ${{ steps.print.outputs.MONGODB_URL }}
    
    steps:
    - name: Print inputs passed to the reusable workflow
      id: print
      shell: bash
      run: |
        MONGODB_URL_D=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$MONGODB_URL") | base64 -w0)
        echo "::set-output name=MONGODB_URL::$(gpg --decrypt --quiet --batch --passphrase "$SECRET" --output - <(echo "$MONGODB_URL_D" | base64 --decode))"

  development:
    name: Development
    uses: mfnizam/barberapp-api/.github/workflows/development.yaml@master
    needs: 
      - env
    with: 
      MONGODB_URL: ${{ needs.env.outputs.MONGODB_URL }}
      
  # release:
  #   if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
  #   name: Release Code
  #   needs: [development]
 
  #   runs-on: ubuntu-latest
    
  #   environment: release

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}

  #   - name: Install dependencies
  #     run: npm install

  #   - name: Release
  #     run: npm run semantic-release
  #     env:
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
